export { default as Home } from './Home';
export { default as GameDetails } from './GameDetails';
export { default as NewReleases } from './NewReleases';
export { default as BestOfYear } from './BestOfYear';
export { default as AllTimeTop } from './AllTimeTop';
export { default as About } from './About';
export { default as NotFound } from './NotFound';
export { default as Search } from './Search';
export { default as Unauthorized } from './Unauthorized';
