export { default as Home } from "./Home";
export { default as GameDetails } from "./GameDetails";
export { default as NewReleases } from "./NewReleases";
export { default as BestOfYear } from "./BestOfYear";
export { default as AllTimeTop } from "./AllTimeTop";
export { default as About } from "./About";
export { default as NotFound } from "./NotFound";
export { default as Search } from "./Search";
export { default as Unauthorized } from "./Unauthorized";
export { default as Login } from "./Login";
export { default as Profile } from "./Profile";
export { default as Settings } from "./Settings";
export { default as Register } from "./Register";
export { default as AdminDashboard } from "./AdminDashboard";
export { default as Help } from "./Help";
export { default as Wishlist } from "./Wishlist";
// export { default as Messages } from './Messages';
// export { default as Notifications } from './Notifications';
